import { ProductData, TabData } from "./types";

export const tabs: TabData[] = [
  { id: "1", label: "Best Seller", value: "best-seller" },
  { id: "2", label: "Top Rated", value: "top-rated" },
  { id: "3", label: "Pregnancy & Postpartum", value: "pregnancy" },
  { id: "4", label: "Milks & Foods", value: "milks" },
  { id: "5", label: "Diapers & Wipes", value: "diapers" },
  { id: "6", label: "Infant", value: "infant" },
  { id: "7", label: "Strollers", value: "strollers" },
];

export const products: ProductData[] = [
  {
    id: "1",
    category: "best-seller",
    title: "Choco Baby Bouncer Balloon",
    brand: "Giggle",
    price: 129.00,
    oldPrice: 159.00,
    discount: 15,
    rating: 5,
    reviews: 2,
    image: "https://images.unsplash.com/photo-1555252333-9f8e92e65df4?q=80&w=2574&auto=format&fit=crop",
    purchases: 1286,
    tag: "HOT",
    description: "Ergonomic bouncer with natural rocking. No batteries required. Suitable from newborn up to 2 years.",
  },
  {
    id: "2",
    category: "best-seller",
    title: "Genber Lil Crunchies, Ounce Canister",
    brand: "Genber",
    price: 1259.00,
    rating: 4.5,
    reviews: 7,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=2630&auto=format&fit=crop",
    purchases: 93,
    description: "Baked corn snack that melts in baby's mouth. Non-GMO and no artificial flavors.",
  },
  {
    id: "3",
    category: "best-seller",
    title: "Gancho Slim Snacker High Chair Grey",
    brand: "Gancho",
    price: 29.00,
    oldPrice: 59.00,
    discount: 45,
    rating: 5,
    reviews: 25,
    image: "https://images.unsplash.com/photo-1616616422329-373815349272?q=80&w=2622&auto=format&fit=crop",
    purchases: 256,
    tag: "NEW",
    description: "Fast-folding high chair with a compact footprint. Easy wipe-clean seat pad.",
  },
  {
    id: "4",
    category: "top-rated",
    title: "Emno Breeze baby carrier",
    brand: "Emno",
    price: 79.00,
    oldPrice: 99.00,
    discount: 20,
    rating: 4.8,
    reviews: 12,
    image: "https://images.unsplash.com/photo-1519689680058-324335c77eba?q=80&w=2670&auto=format&fit=crop",
    purchases: 562,
    tag: "NEW",
    description: "Breathable mesh carrier for maximum airflow. Ergonomic for baby and parent.",
  },
  {
    id: "5",
    category: "best-seller",
    title: "Sharp 49\" Class FHD 1080",
    brand: "Sharp",
    price: 49.00,
    oldPrice: 99.00,
    rating: 4.2,
    reviews: 8,
    image: "https://images.unsplash.com/photo-1556228552-e934751f92e3?q=80&w=2667&auto=format&fit=crop",
    purchases: 1200,
    description: "Crisp Full HD picture quality. Smart functionality with popular apps built-in.",
  },
  {
    id: "6",
    category: "pregnancy",
    title: "Maternity Support Belt",
    brand: "MomCore",
    price: 24.99,
    rating: 4.6,
    reviews: 154,
    image: "https://images.unsplash.com/photo-1555252333-9f8e92e65df4?q=80&w=2574&auto=format&fit=crop", // Placeholder
    purchases: 450,
    description: "Provides gentle support for bump and back. Breathable and adjustable.",
  },
  {
    id: "7",
    category: "milks",
    title: "Organic Infant Formula",
    brand: "PureStart",
    price: 34.50,
    rating: 4.9,
    reviews: 320,
    image: "https://images.unsplash.com/photo-1633596683562-4a47eb4983c5?q=80&w=2672&auto=format&fit=crop", 
    purchases: 2310,
    tag: "HOT",
    description: "Certified organic milk-based powder. No added corn syrup solids.",
  },
   {
    id: "8",
    category: "diapers",
    title: "Eco-Friendly Bamboo Diapers",
    brand: "GreenBaby",
    price: 19.99,
    rating: 4.7,
    reviews: 89,
    image: "https://images.unsplash.com/photo-1519689680058-324335c77eba?q=80&w=2670&auto=format&fit=crop",
    purchases: 890,
    description: "Soft, absorbent, and biodegradable. Hypoallergenic and free of harsh chemicals.",
  }
];
